
backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "_data/site.json"
        label: "Business Info"
        name: "business"
        fields:
          - { label: "Business Name", name: "businessName", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Phone (Link Format)", name: "phoneLink", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "License", name: "license", widget: "string" }
          - { label: "Jobber Link", name: "jobberLink", widget: "string" }
